## Andere Datenquellen

Es ist auch m√∂glich andere Quellen als CSV zu benutzen (z.B. Json, SQL, ...)

In [2]:
import pandas as pd
import requests as r

In [3]:
json = r.get("https://open.er-api.com/v6/latest/USD")

In [5]:
json.json()

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1691971351,
 'time_last_update_utc': 'Mon, 14 Aug 2023 00:02:31 +0000',
 'time_next_update_unix': 1692058381,
 'time_next_update_utc': 'Tue, 15 Aug 2023 00:13:01 +0000',
 'time_eol_unix': 0,
 'base_code': 'USD',
 'rates': {'USD': 1,
  'AED': 3.6725,
  'AFN': 84.115078,
  'ALL': 94.630416,
  'AMD': 385.963763,
  'ANG': 1.79,
  'AOA': 831.44729,
  'ARS': 286.293226,
  'AUD': 1.539101,
  'AWG': 1.79,
  'AZN': 1.69666,
  'BAM': 1.785936,
  'BBD': 2,
  'BDT': 109.384072,
  'BGN': 1.785822,
  'BHD': 0.376,
  'BIF': 2842.323401,
  'BMD': 1,
  'BND': 1.352753,
  'BOB': 6.91961,
  'BRL': 4.904237,
  'BSD': 1,
  'BTN': 82.947095,
  'BWP': 13.496839,
  'BYN': 2.902082,
  'BZD': 2,
  'CAD': 1.344325,
  'CDF': 2391.598008,
  'CHF': 0.876661,
  'CLP': 851.347896,
  'CNY': 7.25919,
  'COP': 3948.513991,
  'CRC': 535.642314,
  'CUP': 24,
  'CVE': 100.686795,
  'CZK': 21.995042,
  'DJF': 177.721,
  'DKK': 6.811386,
  'DOP': 56.603202,
  'DZD': 135.718646,
  'EGP': 30.939496,
  'ERN': 15,
  'ETB': 55.187623,
  'EUR': 0.913137,
  'FJD': 2.237198,
  'FKP': 0.787607,
  'FOK': 6.812332,
  'GBP': 0.787707,
  'GEL': 2.618582,
  'GGP': 0.787607,
  'GHS': 11.194765,
  'GIP': 0.787607,
  'GMD': 61.140308,
  'GNF': 8549.444842,
  'GTQ': 7.85552,
  'GYD': 209.282427,
  'HKD': 7.817553,
  'HNL': 24.587718,
  'HRK': 6.880013,
  'HTG': 136.552765,
  'HUF': 349.638204,
  'IDR': 15291.977585,
  'ILS': 3.730892,
  'IMP': 0.787607,
  'INR': 82.947205,
  'IQD': 1309.900154,
  'IRR': 41963.079538,
  'ISK': 131.472532,
  'JEP': 0.787607,
  'JMD': 154.430102,
  'JOD': 0.709,
  'JPY': 144.780036,
  'KES': 143.504257,
  'KGS': 87.999448,
  'KHR': 4155.395337,
  'KID': 1.538633,
  'KMF': 449.232812,
  'KRW': 1330.492074,
  'KWD': 0.307331,
  'KYD': 0.833333,
  'KZT': 446.483905,
  'LAK': 19301.189298,
  'LBP': 15000,
  'LKR': 319.082664,
  'LRD': 186.372587,
  'LSL': 18.916385,
  'LYD': 4.795569,
  'MAD': 9.866102,
  'MDL': 17.604368,
  'MGA': 4453.925584,
  'MKD': 55.93167,
  'MMK': 2102.130551,
  'MNT': 3493.998316,
  'MOP': 8.05208,
  'MRU': 37.862551,
  'MUR': 45.095089,
  'MVR': 15.437121,
  'MWK': 1079.037227,
  'MXN': 16.998087,
  'MYR': 4.586771,
  'MZN': 63.844754,
  'NAD': 18.916385,
  'NGN': 764.766563,
  'NIO': 36.701857,
  'NOK': 10.428813,
  'NPR': 132.715352,
  'NZD': 1.669091,
  'OMR': 0.384497,
  'PAB': 1,
  'PEN': 3.687083,
  'PGK': 3.609115,
  'PHP': 56.604604,
  'PKR': 287.83733,
  'PLN': 4.051409,
  'PYG': 7300.766361,
  'QAR': 3.64,
  'RON': 4.488547,
  'RSD': 106.955566,
  'RUB': 99.602498,
  'RWF': 1188.527383,
  'SAR': 3.75,
  'SBD': 8.493857,
  'SCR': 13.73832,
  'SDG': 508.925081,
  'SEK': 10.830944,
  'SGD': 1.352755,
  'SHP': 0.787607,
  'SLE': 22.028356,
  'SLL': 22028.355512,
  'SOS': 569.677112,
  'SRD': 38.168001,
  'SSP': 1007.29333,
  'STN': 22.3718,
  'SYP': 12944.978949,
  'SZL': 18.916385,
  'THB': 35.084224,
  'TJS': 10.920718,
  'TMT': 3.500699,
  'TND': 3.073356,
  'TOP': 2.336374,
  'TRY': 27.070783,
  'TTD': 6.767349,
  'TVD': 1.538633,
  'TWD': 31.860247,
  'TZS': 2502.098371,
  'UAH': 36.788073,
  'UGX': 3742.073596,
  'UYU': 38.060254,
  'UZS': 12239.497601,
  'VES': 31.5251,
  'VND': 23757.627831,
  'VUV': 120.495535,
  'WST': 2.747204,
  'XAF': 598.977082,
  'XCD': 2.7,
  'XDR': 0.747499,
  'XOF': 598.977082,
  'XPF': 108.966187,
  'YER': 249.938273,
  'ZAR': 18.918457,
  'ZMW': 19.143163,
  'ZWL': 4654.209985}}

In [9]:
json.json()['rates']

{'USD': 1,
 'AED': 3.6725,
 'AFN': 84.115078,
 'ALL': 94.630416,
 'AMD': 385.963763,
 'ANG': 1.79,
 'AOA': 831.44729,
 'ARS': 286.293226,
 'AUD': 1.539101,
 'AWG': 1.79,
 'AZN': 1.69666,
 'BAM': 1.785936,
 'BBD': 2,
 'BDT': 109.384072,
 'BGN': 1.785822,
 'BHD': 0.376,
 'BIF': 2842.323401,
 'BMD': 1,
 'BND': 1.352753,
 'BOB': 6.91961,
 'BRL': 4.904237,
 'BSD': 1,
 'BTN': 82.947095,
 'BWP': 13.496839,
 'BYN': 2.902082,
 'BZD': 2,
 'CAD': 1.344325,
 'CDF': 2391.598008,
 'CHF': 0.876661,
 'CLP': 851.347896,
 'CNY': 7.25919,
 'COP': 3948.513991,
 'CRC': 535.642314,
 'CUP': 24,
 'CVE': 100.686795,
 'CZK': 21.995042,
 'DJF': 177.721,
 'DKK': 6.811386,
 'DOP': 56.603202,
 'DZD': 135.718646,
 'EGP': 30.939496,
 'ERN': 15,
 'ETB': 55.187623,
 'EUR': 0.913137,
 'FJD': 2.237198,
 'FKP': 0.787607,
 'FOK': 6.812332,
 'GBP': 0.787707,
 'GEL': 2.618582,
 'GGP': 0.787607,
 'GHS': 11.194765,
 'GIP': 0.787607,
 'GMD': 61.140308,
 'GNF': 8549.444842,
 'GTQ': 7.85552,
 'GYD': 209.282427,
 'HKD': 7.817553,
 'HNL': 24.587718,
 'HRK': 6.880013,
 'HTG': 136.552765,
 'HUF': 349.638204,
 'IDR': 15291.977585,
 'ILS': 3.730892,
 'IMP': 0.787607,
 'INR': 82.947205,
 'IQD': 1309.900154,
 'IRR': 41963.079538,
 'ISK': 131.472532,
 'JEP': 0.787607,
 'JMD': 154.430102,
 'JOD': 0.709,
 'JPY': 144.780036,
 'KES': 143.504257,
 'KGS': 87.999448,
 'KHR': 4155.395337,
 'KID': 1.538633,
 'KMF': 449.232812,
 'KRW': 1330.492074,
 'KWD': 0.307331,
 'KYD': 0.833333,
 'KZT': 446.483905,
 'LAK': 19301.189298,
 'LBP': 15000,
 'LKR': 319.082664,
 'LRD': 186.372587,
 'LSL': 18.916385,
 'LYD': 4.795569,
 'MAD': 9.866102,
 'MDL': 17.604368,
 'MGA': 4453.925584,
 'MKD': 55.93167,
 'MMK': 2102.130551,
 'MNT': 3493.998316,
 'MOP': 8.05208,
 'MRU': 37.862551,
 'MUR': 45.095089,
 'MVR': 15.437121,
 'MWK': 1079.037227,
 'MXN': 16.998087,
 'MYR': 4.586771,
 'MZN': 63.844754,
 'NAD': 18.916385,
 'NGN': 764.766563,
 'NIO': 36.701857,
 'NOK': 10.428813,
 'NPR': 132.715352,
 'NZD': 1.669091,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.687083,
 'PGK': 3.609115,
 'PHP': 56.604604,
 'PKR': 287.83733,
 'PLN': 4.051409,
 'PYG': 7300.766361,
 'QAR': 3.64,
 'RON': 4.488547,
 'RSD': 106.955566,
 'RUB': 99.602498,
 'RWF': 1188.527383,
 'SAR': 3.75,
 'SBD': 8.493857,
 'SCR': 13.73832,
 'SDG': 508.925081,
 'SEK': 10.830944,
 'SGD': 1.352755,
 'SHP': 0.787607,
 'SLE': 22.028356,
 'SLL': 22028.355512,
 'SOS': 569.677112,
 'SRD': 38.168001,
 'SSP': 1007.29333,
 'STN': 22.3718,
 'SYP': 12944.978949,
 'SZL': 18.916385,
 'THB': 35.084224,
 'TJS': 10.920718,
 'TMT': 3.500699,
 'TND': 3.073356,
 'TOP': 2.336374,
 'TRY': 27.070783,
 'TTD': 6.767349,
 'TVD': 1.538633,
 'TWD': 31.860247,
 'TZS': 2502.098371,
 'UAH': 36.788073,
 'UGX': 3742.073596,
 'UYU': 38.060254,
 'UZS': 12239.497601,
 'VES': 31.5251,
 'VND': 23757.627831,
 'VUV': 120.495535,
 'WST': 2.747204,
 'XAF': 598.977082,
 'XCD': 2.7,
 'XDR': 0.747499,
 'XOF': 598.977082,
 'XPF': 108.966187,
 'YER': 249.938273,
 'ZAR': 18.918457,
 'ZMW': 19.143163,
 'ZWL': 4654.209985}

In [13]:
jsonDF = pd.DataFrame.from_dict(json.json()['rates'], orient="index")
jsonDF = jsonDF.rename(columns={0: "Exchange Rates"})
jsonDF

     Exchange Rates
USD        1.000000
AED        3.672500
AFN       84.115078
ALL       94.630416
AMD      385.963763
..              ...
XPF      108.966187
YER      249.938273
ZAR       18.918457
ZMW       19.143163
ZWL     4654.209985

[162 rows x 1 columns]

In [14]:
readJson = pd.read_json("https://open.er-api.com/v6/latest/USD")

In [15]:
readJson

,result,provider,documentation,terms_of_use,time_last_update_unix,time_last_update_utc,time_next_update_unix,time_next_update_utc,time_eol_unix,base_code,rates
AED,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,3.672500
AFN,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,84.115078
ALL,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,94.630416
AMD,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,385.963763
ANG,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,1.790000
...,...,...,...,...,...,...,...,...,...,...,...
XPF,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,108.966187
YER,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,249.938273
ZAR,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,18.918457
ZMW,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,19.143163
ZWL,success,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,1691971351,"Mon, 14 Aug 2023 00:02:31 +0000",1692058381,"Tue, 15 Aug 2023 00:13:01 +0000",0,USD,4654.209985

## Daten aus einer Datenbank

In [20]:
import sqlite3 as sql
connection = sql.connect("Test.db")
cursor = connection.cursor()

# cursor.execute("create table test(id integer primary key, name varchar(30))")
cursor.execute("insert into test (id, name) values(1, 'Max1')")
cursor.execute("insert into test (id, name) values(2, 'Max2')")
cursor.execute("insert into test (id, name) values(3, 'Max3')")

data = pd.read_sql("select * from test", con=connection)
data

OperationalError: database is locked

## Export von Daten

In [21]:
readJson.to_csv("Json.csv")

In [22]:
readJson.to_json("Json.json")

In [24]:
import openpyxl
readJson.to_excel("Json.xlsx")